# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  pipelines:
    - pipeline: buildContosoAir
      source: buildContosoAir
      trigger:
        branches:
          include:
            - master
pool:
  vmImage: ubuntu-latest
steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'specific'
      project: 'ef11f37e-aaf6-4dfd-b51a-058da6c4c926'
      definition: '15'
      specificBuildWithTriggering: true
      buildVersionToDownload: 'latest'
      targetPath: '$(Pipeline.Workspace)'
      
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'servconn'
      subscriptionId: '92b040d4-64f8-48fc-a066-ba79632ef27b'
      action: 'Create Or Update Resource Group'
      resourceGroupName: '$(resourcegroup)'
      location: 'uksouth'
      templateLocation: 'Linked artifact'
      csmFile: '$(Pipeline.Workspace)/drop/Templates/azuredeploy.json'
      csmParametersFile: '$(Pipeline.Workspace)/drop/Templates/azuredeploy.parameters.json'
      overrideParameters: '-p_environment $(web_environment) -p_site_prefix $(web_prefix) -p_site_web_name $(web_site)'
      deploymentMode: 'Incremental'
      
  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'servconn'
      appType: 'webApp'
      WebAppName: '$(web_prefix)-$(web_site)-$(web_environment)'
      packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
